Find movies
darkqq/besmart-kinopoisk-service pull request #4
Opened 2023-09-12 09:46 UTC by Makseke

2023-09-12 09:57 UTC, darkqq commented on src/main/java/com/besmartkinopoiskservice/repository/MovieRepository.java
> +    List<MovieEntity> findAllWhereYearMore(LocalDate year);
Можно было без квери написать)
findAllByYearAfter (по хорошему так и назвать метод, а то More как-то не вяжется)

2023-09-12 10:11 UTC, darkqq requested changes
:sad:

2023-09-12 10:11 UTC, darkqq commented on src/main/java/com/besmartkinopoiskservice/repository/MovieRepository.java
> +    List<MovieEntity> findAllWhereYearMore(LocalDate year);
Можно было без квери написать) findAllByYearAfter (по хорошему так и назвать метод, а то More как-то не вяжется)

2023-09-12 10:11 UTC, darkqq commented on src/main/java/com/besmartkinopoiskservice/repository/MovieRepository.java
> +    List<MovieEntity> findAllWhereTitleLike(String title);
Такая же шляпа, ты можешь не писать квери запросы, на простые запросы достаточно автогенерации. Если уже метод выходит супердлинный или modifying то тогда уже надо писать запрос)

2023-09-12 10:11 UTC, darkqq commented on src/main/java/com/besmartkinopoiskservice/security/SecurityConfig.java
> +                        .requestMatchers(new AntPathRequestMatcher("/movie/add")).hasAuthority(Role.ADMIN.toString())
Почитай всё таки про аннотационный метод обозначения доступов, чтобы не надо было потом лазить и менять урлы.
Либо все урлы в отдельный интерфейс, чтобы можно было переиспользовать

2023-09-12 10:11 UTC, darkqq commented on src/main/java/com/besmartkinopoiskservice/service/impl/AuthenticationServiceImpl.java
> +        System.out.println(request.getUsername());
це шо

2023-09-12 10:11 UTC, darkqq commented on src/main/java/com/besmartkinopoiskservice/service/impl/MovieServiceImpl.java
> +        if (movieRepository.existsByTitle(request.getTitle()) && movieRepository.existsByPremiere(premiere)) {
Никто не запрещает двум фильмам выходить в один день, не думаю что это сюда подходит)

2023-09-12 10:11 UTC, darkqq commented on src/main/java/com/besmartkinopoiskservice/service/impl/MovieServiceImpl.java
> +        );
ЫЫЫЫЫЫ


LocalDate.parse();


А вообще у тебя происходит автоматическая сериализация даты в LocalDate или LocalDateTime. Почитай про эти два класса в сериализации

2023-09-12 10:11 UTC, darkqq commented on src/main/java/com/besmartkinopoiskservice/service/impl/MovieServiceImpl.java
> +    public GetMoviePageResponseTO getMoviePage(String title) throws ServiceException {
Ты тут отдаешь не страницу, а детали)
Приывыкай что работаешь не на фронте!)

2023-09-12 10:11 UTC, darkqq commented on src/main/java/com/besmartkinopoiskservice/service/impl/MovieServiceImpl.java
> +            Collections.sort(movie, Comparator.comparingDouble(MovieEntity::getCurrentRating));
А вот тут можно было уже и запросы пописать)

Либо https://www.baeldung.com/spring-data-jpa-pagination-sorting

2023-09-12 10:11 UTC, darkqq commented on src/main/java/com/besmartkinopoiskservice/controller/MovieController.java
>      }
getMovieList

getMovies

etc. 
Я уже вроде говорил)

2023-09-12 10:11 UTC, darkqq commented on src/main/java/com/besmartkinopoiskservice/util/mapper/MoviePageMapper.java
> +        }
```suggestion
        List<CommentDetailsTO> commentDetails = new ArrayList<>();
        for (int i = 0; i < entity.getComments().size(); i++){
            commentDetails.add(new CommentMapper()[кину в голову кирпичом, если не будешь пользоваться статическими классами. У тебя прилага ляжет если ты создашь по мапперу на каждый коммент допустим из 10000].toDto(entity.getComments().get(i)));
        }

        равносильно

        List<CommentDetailsTO> commentDetails = entity.getComments().stream().map(CommentMapper::toDto).toList();

```

2023-09-12 10:11 UTC, darkqq commented on src/main/java/com/besmartkinopoiskservice/util/mapper/MoviePageMapper.java
> +        }
Кажется второй вариант выглядит быстрее и симпатичнее)

2023-09-12 10:11 UTC, darkqq commented on src/main/java/com/besmartkinopoiskservice/util/GetAverageRating.java
> +public class GetAverageRating {
Прикольно ты придумал класс называть в честь метода)

RatingCalculatorUtil чем не понравилось?))

2023-09-12 10:37 UTC, Makseke commented on src/main/java/com/besmartkinopoiskservice/service/impl/MovieServiceImpl.java
> +        if (movieRepository.existsByTitle(request.getTitle()) && movieRepository.existsByPremiere(premiere)) {
Два фильма с одним названием в один день?

2023-09-12 13:10 UTC, darkqq commented on src/main/java/com/besmartkinopoiskservice/service/impl/MovieServiceImpl.java
> +        if (movieRepository.existsByTitle(request.getTitle()) && movieRepository.existsByPremiere(premiere)) {
Всё гуд, мой косяк

2023-09-12 13:15 UTC, darkqq requested changes

2023-09-12 13:15 UTC, darkqq commented on src/main/java/com/besmartkinopoiskservice/controller/MovieController.java
>      @GetMapping("")
сделай тут GetMappling("/list"), а то на get /movie получается, не оч

2023-09-14 14:06 UTC, darkqq requested changes

2023-09-14 14:06 UTC, darkqq commented on src/main/java/com/besmartkinopoiskservice/to/request/movierequest/CreateMoviePageRequestTO.java
>      private String title;
Почему ты так тянешь за собой этот Page?))
Ты создаешь не page а просто movie в базе, которое с page из общего имеет только данные)

2023-09-14 14:06 UTC, darkqq commented on src/main/java/com/besmartkinopoiskservice/controller/CommentController.java
> +    @GetMapping("/comments")
/comment/comments

Мб лучше /comment/list ?

2023-09-14 14:06 UTC, darkqq commented on src/main/java/com/besmartkinopoiskservice/controller/CommentController.java
> +    @PutMapping("/comments/update")
У тебя везде получился двойной префикс, @RequestMapping, который ты указываешь над контроллером автоматом добавляет тебе вставленную строку в путь. + можно не писать /update а сделать пустой PUT запрос на /comment (или /commentary, мб красивее будет)

2023-09-14 14:06 UTC, darkqq commented on src/main/java/com/besmartkinopoiskservice/controller/CommentController.java
> +    @PutMapping("/comments/add")
POST

мы создаем новую запись

2023-09-14 14:06 UTC, darkqq commented on src/main/java/com/besmartkinopoiskservice/controller/CommentController.java
> +    @PutMapping("/comments/delete")
DeleteMapping

2023-09-14 14:06 UTC, darkqq commented on src/main/java/com/besmartkinopoiskservice/controller/MovieController.java
> +        return ResponseEntity.ok(movieService.addMovieToDatabase(request));
А куда муви еще можно добавлять?

мб лучше createMovie?

2023-09-14 14:06 UTC, darkqq commented on src/main/java/com/besmartkinopoiskservice/controller/MovieController.java
> +    public ResponseEntity<EmptyResponseTO> updateMovieImage(@RequestParam("movieid") UUID movieId, @RequestParam("image") MultipartFile image) throws IOException {
У тебя PutMapping, зачем в RequestParam пихать, если в путе есть тело)

PUT/POST - тело запроса есть, надо использовать

GET/DELETE - тела нет, нужны параметры

2023-09-14 14:06 UTC, darkqq commented on src/main/java/com/besmartkinopoiskservice/exception/WebExceptionHandler.java
> +    }
Вообще было бы неплохо сделать кастомную ошибку на авторизацию с текстом того что неправильно, а то как-то не понятно как всё это дело на фронте хендлить

2023-09-14 14:06 UTC, darkqq commented on src/main/java/com/besmartkinopoiskservice/repository/ImageRepository.java
> +@Repository
Тебе не надо это трекать как репозиторий, репозиторий у тебя ходит в базу, у которой есть ошибки. FileSystem ошибки эта аннотация не хендлит

2023-09-14 14:06 UTC, darkqq commented on src/main/java/com/besmartkinopoiskservice/service/impl/MovieServiceImpl.java
> +                throw new ServiceException("Фильмов вышедших в этот год или позднее не существует");
Не надо кидать исключения, просто отдай пустой список

2023-09-14 14:06 UTC, darkqq commented on src/main/java/com/besmartkinopoiskservice/service/impl/MovieServiceImpl.java
> +            Set<MovieEntity> movieSet = new HashSet<>(movie);
Интересный подход, но лучше всё таки одним запросом это дело фильтровать из базы)
Она умеет находить по многим параметрам через OR или AND

2023-09-14 14:06 UTC, darkqq commented on src/main/java/com/besmartkinopoiskservice/service/impl/MovieServiceImpl.java
> +        if (sortType == "year") {
В отдельный енам вынести

2023-09-14 14:06 UTC, darkqq commented on src/main/java/com/besmartkinopoiskservice/service/impl/MovieServiceImpl.java
> +        } else if (sortType == "rating") {
В отдельный енам вынести

2023-09-14 14:06 UTC, darkqq commented on src/main/java/com/besmartkinopoiskservice/service/impl/MovieServiceImpl.java
> +    public EmptyResponseTO updateMovieImage(UUID movieId, MultipartFile image) throws IOException {
И куда это полтетит?

2023-09-14 14:06 UTC, darkqq commented on src/main/java/com/besmartkinopoiskservice/service/impl/MovieServiceImpl.java
> +    public ResponseEntity<byte[]> getMovieImage(UUID movieId) throws IOException, ServiceException {
Твои сервисы могут выбрасывать только исключения, которые ты обработал в ExceptionHandler'e IOException вообще не выглядит как что-то нормальное для пользователя)

2023-09-14 14:06 UTC, darkqq commented on src/main/java/com/besmartkinopoiskservice/to/response/movieresposes/GetMoviePageResponseTO.java
> -    private MoviePageDetailsTO movieDetails;
zachem

сделай extends MovieDetailsTO и не придется делать стократную вложенность

2023-09-14 14:06 UTC, darkqq commented on src/main/java/com/besmartkinopoiskservice/util/mapper/MoviePageMapper.java
> +                new RatingCalculatorUtil().getAverageRating(entity.getRating()),
?

2023-09-14 14:06 UTC, darkqq commented on src/main/java/com/besmartkinopoiskservice/util/RatingCalculatorUtil.java
> +        double averageRating = 0;
public static double

2023-09-14 14:06 UTC, darkqq commented on pom.xml
> +		</dependency>
чем тебе не понравились зависимости которые у тебя уже есть?

```
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>

        <dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>

```

2023-09-14 14:06 UTC, darkqq commented on src/main/java/com/besmartkinopoiskservice/security/ApplicationConfig.java
>      private final UserRepository userRepository;
Тебе не нужен тут Autowired, у тебя есть RequiredArgsConstructor

2023-09-14 14:06 UTC, darkqq commented on src/main/java/com/besmartkinopoiskservice/security/ApplicationConfig.java
> +    }
why

чем тебе не понравилась аннотация @Component над репозиторием?

2023-09-22 08:06 UTC, merged